name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py-version: [3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python ${{ matrix.py-version }} on ${{ matrix.os }} 
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py-version }}
        
